class ConstantVariables:
    WINDOW_WIDTH = 800
    WINDOW_HEIGHT = 500
    TILE_WIDTH = 20
    NB_ROW = WINDOW_HEIGHT / TILE_WIDTH
    NB_COLUMN = WINDOW_WIDTH / TILE_WIDTH

    NETWORK_HEADER_LENGTH = 10
    NETWORK_IP = "192.168.0.19"
    NETWORK_PORT = 5555

